[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://clover-backend.fly.dev/wnba/query"
    Access-Control-Request-Method = POST