// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GameFilter struct {
	TeamID    *int    `json:"teamID"`
	PlayerID  *int    `json:"playerID"`
	GameID    *string `json:"gameID"`
	Season    *string `json:"season"`
	StartDate *string `json:"startDate"`
	EndDate   *string `json:"endDate"`
}

type PlayerFilter struct {
	Name     *string `json:"name"`
	PlayerID *int    `json:"playerID"`
	Season   *string `json:"season"`
	Position *string `json:"position"`
	TeamAbr  *string `json:"teamABR"`
	TeamID   *int    `json:"teamID"`
}

type ProjectionFilter struct {
	Sportsbook *string `json:"sportsbook"`
	PlayerName *string `json:"playerName"`
	PlayerID   *int    `json:"playerID"`
	StartDate  *string `json:"startDate"`
	EndDate    *string `json:"endDate"`
	TeamID     *int    `json:"teamID"`
	OpponentID *int    `json:"opponentID"`
}

type Target struct {
	Target float64 `json:"target"`
	Type   string  `json:"type"`
}

type TeamFilter struct {
	Name         *string `json:"name"`
	TeamID       *int    `json:"teamID"`
	Abbreviation *string `json:"abbreviation"`
}
