// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PlayerFilter struct {
	Name     *string `json:"name" bson:"first_name"`
	PlayerID *int    `json:"playerID" bson:"playerID"`
	Season   *string `json:"season" bson:"season"`
	Position *string `json:"position" bson:"position"`
}

type Team struct {
	Name         string `json:"name" bson:"name"`
	TeamID       int    `json:"teamID" bson:"teamID"`
	Abbreviation string `json:"abbreviation" bson:"abbreviation"`
	Location     string `json:"location" bson:"location"`
	NumWins      int    `json:"numWins" bson:"numWins"`
	NumLoss      int    `json:"numLoss" bson:"numLoss"`
}

type TeamFilter struct {
	Name         *string `json:"name" bson:"name"`
	TeamID       *int    `json:"teamID" bson:"teamID"`
	Abbreviation *string `json:"abbreviation" bson:"abbreviation"`
}
